version: '2'

services:
  firefly-app:
    environment:
      - FF_APP_ENV=local
    volumes:
      - firefly-app-storage:/var/www/firefly-iii/storage

volumes:
  firefly-app-storage:
    driver: local
